# Облегчённый мониторинг для одного рабочего узла.

# Вместо множества стандартных оповещений
# создадим два собственных для диплома.
defaultRules:
  create: false

# Эти компоненты управляются Yandex Cloud.
kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

grafana:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

prometheus:
  prometheusSpec:
    retention: 1d
    resources:
      requests:
        cpu: 150m
        memory: 384Mi
      limits:
        cpu: 800m
        memory: 1200Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 256Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
