# Production configuration for Yandex Managed Kubernetes.
# Image tag will be updated automatically by CI/CD.

replicaCount: 1

image:
  repository: ghcr.io/gogeezy/web-go-prg
  pullPolicy: IfNotPresent
  tag: sha-4c2f2b5c4eb121201a3c514576ba9d3a0df0a35f

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: 158.160.233.167.nip.io
      paths:
        - path: /
          pathType: Prefix

serviceMonitor: true

prometheusRule: true
