# Production configuration for Yandex Managed Kubernetes.
# Image tag will be updated automatically by CI/CD.

replicaCount: 1

image:
  repository: ghcr.io/gogeezy/web-go-prg
  pullPolicy: IfNotPresent
  tag: sha-c348c82a525d520ae94615c643c8656676e0542d

autoscaling:
  enabled: false

ingress:
  enabled: false
