# Production configuration for Yandex Managed Kubernetes.
# Image tag will be updated automatically by CI/CD.

replicaCount: 1

image:
  repository: ghcr.io/gogeezy/web-go-prg
  pullPolicy: IfNotPresent
  tag: sha-691ec0b637e2cdaf5b8c6a1d9fad2eea2db36a01

autoscaling:
  enabled: false

ingress:
  enabled: false
